sylius_resource:
    resources:
        app.board:
            driver: doctrine/orm
            templates: :Board
            classes:
                model: AppBundle\Entity\Board
        app.board_list:
            driver: doctrine/orm
            templates: :BoardList
            classes:
                model: AppBundle\Entity\BoardList