sylius_resource:
    resources:
        app.board:
            driver: doctrine/orm
            templates: :Board
            classes:
                model: AppBundle\Entity\Board
                controller: AppBundle\Controller\BoardController
        app.board_list:
            driver: doctrine/orm
            templates: :BoardList
            classes:
                model: AppBundle\Entity\BoardList
                controller: AppBundle\Controller\BoardListController
        app.card:
            driver: doctrine/orm
            templates: :Card
            classes:
                model: AppBundle\Entity\Card
                controller: AppBundle\Controller\CardController
