homepage:
    pattern: /
    methods: [GET]
    defaults:
        _controller: app.controller.board:indexAction

app_board_create:
    pattern: /boards/new
    methods: [GET, POST]
    defaults:
        _controller: app.controller.board:createAction
        _sylius:
            redirect: homepage

app_board_delete:
    pattern: /boards/{id}
    methods: [DELETE]
    defaults:
        _controller: app.controller.board:deleteAction
        _sylius:
            redirect: homepage

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    
app_board_create_json:
    pattern: /boards/new/json
    methods: [GET]
    defaults:
      _controller: app.controller.board:createAction
      _format: json
      
app_board_delete_json:
    pattern: /boards/delete/json
    methods: [GET]
    defaults:
      _controller: app.controller.board:deleteAction
      _format: json