app_board_create:
    pattern: /new
    methods: [GET, POST]
    defaults:
        _controller: app.controller.board:createAction
        _sylius:
            redirect: homepage

app_board_show:
    pattern: /{boardId}
    methods: [GET]
    defaults:
        _controller: app.controller.boardList:allForBoardAction

app_board_star:
    pattern: /{id}/star
    methods: [GET, PUT]
    defaults:
        _controller: app.controller.board:starAction

app_board_unstar:
    pattern: /{id}/unstar
    methods: [GET, PUT]
    defaults:
        _controller: app.controller.board:unstarAction

app_board_archive:
    pattern: /{id}/archive
    methods: [GET, PUT]
    defaults:
        _controller: app.controller.archive:archiveBoardAction

app_board_unarchive:
    pattern: /{id}/unarchive
    methods: [GET, PUT]
    defaults:
        _controller: app.controller.archive:unarchiveBoardAction

app_board_delete:
    pattern: /{id}
    methods: [DELETE]
    defaults:
        _controller: app.controller.board:deleteAction
        _sylius:
            redirect: homepage

app_board_update:
    pattern: /{id}/edit
    methods: [GET, PUT, POST]
    defaults:
        _controller: app.controller.board:updateAction
        _sylius:
            redirect:
                route: app_board_show
                parameters: { boardId: $id }

app_board_create_json:
    pattern: /new/json
    methods: [POST]
    defaults:
      _controller: app.controller.board:createAction
      _format: json

app_board_delete_json:
    pattern: /delete/json
    methods: [DELETE]
    defaults:
      _controller: app.controller.board:deleteAction
      _format: json

app_board_list:
    resource: @AppBundle/Resources/config/routing/board_list.yml
    prefix: /{boardId}/board-list

app_card_move:
    pattern: /{id}/{cardId}/{targetBoardListId}
    methods: [PUT, PATCH, GET]
    defaults:
        _controller: app.controller.card:moveAction
    requirements:
        id:  \d+
        cardId:  \d+
        targetBoardListId:  \d+
