app_board_list_create:
    pattern: /new
    methods: [GET, POST]
    defaults:
        _controller: app.controller.boardList:createAction
        _sylius:
            redirect: homepage

app_board_list_delete:
    pattern: /{id}
    methods: [DELETE]
    defaults:
        _controller: app.controller.boardList:deleteAction
        _sylius:
            redirect: homepage

app_board_list_update:
    pattern: /{id}/edit
    methods: [GET, PUT, POST]
    defaults:
        _controller: app.controller.boardList:updateAction
        _sylius:
            redirect: app_board_list_update