app_admin_index:
    pattern: /
    methods: [GET]
    defaults:
        _controller: AppBundle:Admin:index

app_admin_organizations:
    resource: @AppBundle/Resources/config/routing/admin/organization.yml
    prefix: /organizations

app_admin_labels:
    resource: @AppBundle/Resources/config/routing/admin/label.yml
    prefix: /labels
