app_admin_index:
    pattern: /
    methods: [GET]
    defaults:
        _controller: AppBundle:Admin:index

app_admin:
    resource: @AppBundle/Resources/config/routing/admin/organization.yml
    prefix: /organizations
