homepage:
    pattern: /
    methods: [GET]
    defaults:
        _controller: app.controller.board:allForUserAction

admin:
    pattern: /admin/
    methods: [GET]
    defaults:
        _controller: AppBundle:Admin:index

app_board:
    resource: @AppBundle/Resources/config/routing/board.yml
    prefix: /boards
