services:
    app.form.type.board:
        class: AppBundle\Form\Type\BoardType
        tags:
            - { name: form.type, alias: app_board }
    app.form.type.board_list:
        class: AppBundle\Form\Type\BoardListType
        tags:
            - { name: form.type, alias: app_board_list }
    app.form.type.card:
        class: AppBundle\Form\Type\CardType
        tags:
            - { name: form.type, alias: app_card }
    app.form.type.organization:
        class: AppBundle\Form\Type\OrganizationType
        tags:
            - { name: form.type, alias: app_organization }
