services:
    app.form.type.board:
        class: AppBundle\Form\Type\BoardType
        tags:
            - { name: form.type, alias: app_board }
    app.form.type.board_list:
        class: AppBundle\Form\Type\BoardListType
        tags:
            - { name: form.type, alias: app_board_list }
